[package]
name = "abax_library"
version = "0.1.1"
authors = []
edition = "2021"

[dependencies]
ink = { version = "4.3", default-features = false }
scale = { package = "parity-scale-codec", version = "3.5.0", default-features = false, features = [
    "derive",
] }
scale-info = { version = "2.7", default-features = false, features = [
    "derive",
], optional = true }

pendzl = { path = "../../../pendzl-contracts", default-features = false, features = [
    "psp22",
    "psp34",
    "ownable",
    "pausable",
    "access_control",
] }
primitive-types = { version = "0.12.1", default-features = false, features = [
    "codec",
] }

[lib]
name = "abax_library"
path = "lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",

    # These dependencies
    "pendzl/std",
    "primitive-types/std",
    "primitive-types/scale-info",
]
